version: '3.8'

services:
  nodeA:
    image: rastasheep/ubuntu-sshd:18.04
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    ports:
      - "2222:22"
    networks:
      ansible_network:
        ipv4_address: 172.20.0.2

  nodeB:
    image: rastasheep/ubuntu-sshd:18.04
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    ports:
      - "2223:22"
    networks:
      ansible_network:
        ipv4_address: 172.20.0.3

networks:
  ansible_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16

