- hosts: all
  gather_facts: no
  tasks:
    - name: Retrieve and process JSON data
      include_role:
        name: json_retrieval
- hosts: nodeA
  gather_facts: no
  roles:
    - process_nodeA

- hosts: nodeB
  gather_facts: no
  roles:
    - process_nodeB
