---
- name: Retrieve JSON data
  uri:
    url: "{{ json_data_url }}"
    method: GET
    return_content: yes
  register: json_response

- name: Extract 'form' entry from JSON
  set_fact:
    form_data: "{{ json_response.json.form }}"

- name: Create a list of all labels prefixed with 'TRAYPORT'
  set_fact:
    trayport_labels: "{{ trayport_labels | default([]) + ['TRAYPORT' + item] }}"
  loop: "{{ form_data.formFieldGroups | json_query('[].fields[].label') }}"
  when: item != ''

- name: Remove duplicates from the list
  set_fact:
    trayport_labels: "{{ trayport_labels | unique }}"

- name: Debug the list of processed labels
  debug:
    var: trayport_labels
  tags: [ never, debug ]


