---
- name: Retrieve JSON data
  uri:
    url: "https://forms.hsforms.com/embed/v3/form/7257359/3e06f85f-0325-4dd3-b663-82284f38ff47/json"
    method: GET
    return_content: yes
  register: json_response

- name: Extract 'form' entry from JSON
  set_fact:
    form_data: "{{ json_response.json.form }}"
# - name: Debug form_data elements
#   debug:
#     msg: "{{ form_data }}"
- name: Create a list of all labels prefixed with 'TRAYPORT'
  set_fact:
    trayport_labels: "{{ trayport_labels | default([]) + ['TRAYPORT' + item] }}"
  loop: "{{ form_data.formFieldGroups | json_query('[].fields[].label') }}"
  when: item != ''

- name: Debug the list of processed labels
  debug:
    var: trayport_labels


