---
- name: Odd Length
  tags: nodeA
  block:
    - name: Create a dictionary of labels with odd length and their lengths
      set_fact:
        labels_odd_length: "{{ labels_odd_length | default({}) | combine({item: item | length}) }}"
      loop: "{{ trayport_labels }}"
      when: item | length is odd

    - name: Debug the labels_odd_length variable
      debug:
        var: labels_odd_length

    - name: Calculate the sum of all odd lengths
      set_fact:
        total_length_odd: "{{ labels_odd_length.values() | map('int') | sum }}"

    - name: Print the sum message for nodeA
      debug:
        msg: "The sum of all the nodeA lengths is: {{ 'odd' if (total_length_odd | int) % 2 != 0 else 'even' }}. Value is {{ total_length_odd }}"


- name: Even Length
  tags: nodeB
  block:
    - name: Collect labels with even length
      set_fact:
        labels_even: "{{ labels_even | default([]) + [item] }}"
      loop: "{{ trayport_labels }}"
      when: item | length is even

    - name: Create an ordered list of unique alphanumeric characters from even labels
      set_fact:
        unique_chars_even: "{{ labels_even | join('') | regex_replace('[^a-zA-Z0-9]', '') | list | map('lower') | unique | sort }}"

    - name: Calculate the sum of all even lengths
      set_fact:
        total_length_even: "{{ labels_even | map('length') | sum }}"

    - name: Print the sum message for even lengths
      debug:
        msg: "The sum of all the nodeB lengths is: {{ 'odd' if (total_length_even | int) % 2 != 0 else 'even' }}"

